### ISSUE TITLE
Elo Decay

### ISSUE THREAD

**Issue by SnoreSmash** [JettJengaGod/scoresheetbot#128]
Implement Elo Decay.
- Only applies to top 40% of crews
- If, at any point, a crew drops out of that top 40%, their timer is nullified/reset to 0 until they come back into top 40%. This is the intended scenario for most inactive top crews, to drop out of the top 40% by elo decay and then just live on one or two cbs a month.
- Timer starts fresh on the day it's implemented (no retroactive decays get applied) 

1 wk = no decay, reminder to leaders
2 wk = -25
2.5 wk = reminder to leaders
3 wk = -50
3.5 wk = reminder to leaders
1 month = -100

**Comment by JettJengaGod** [comment]
https://github.com/JettJengaGod/scoresheetbot/commit/4e5ba7ce74f6b9eeb42d9679c8bcf67f5d009a9a
