### ISSUE TITLE
Clean up flairing chat

### ISSUE THREAD

**Issue by SnoreSmash** [JettJengaGod/scoresheetbot#23]
Needs some more ideas/discussion.. probably best option is to delete the original command, and retain only the bot output (success/failure). All bot messages would need tweaked so that the command user is tagged, and it is easy to interpret what the original command was.

**Comment by SnoreSmash** [comment]
Delete original command, have bot respond with success/failure.
All bot messages show which user initiated command.

e.g.
@SnoreSmash: Successfully flaired @JettJengaGod for DBQ.
@SnoreSmash: sovietwalnut69 is not in the overflow server and Bread and Butter Bois is an overflow crew. 
@SnoreSmash: You can't flair people for other crews unless you are Staff.

**Comment by JettJengaGod** [comment]
First part is done, possible later update to remove all non commands from the chat.
