### ISSUE TITLE
Error code modifications

### ISSUE THREAD

**Issue by SnoreSmash** [JettJengaGod/scoresheetbot#28]
![image](https://user-images.githubusercontent.com/75290252/102169847-116c6b80-3e61-11eb-9883-66a75022af62.png)
- _Read if multi-user flairing is intended, provide appropriate error message_

![image](https://user-images.githubusercontent.com/75290252/102169868-1e895a80-3e61-11eb-8c3a-ad12a402f95c.png)
- "The read operation timed out. Try again after 60 seconds."

![image](https://user-images.githubusercontent.com/75290252/102169906-32cd5780-3e61-11eb-96a2-925e38c553fa.png)
- _Tag the player, since the `,flair` command will be deleted soon after and the ping will have no source_

![image](https://user-images.githubusercontent.com/75290252/102169987-61e3c900-3e61-11eb-8ea8-5242585576ad.png)
- ???

![image](https://user-images.githubusercontent.com/75290252/102170037-73c56c00-3e61-11eb-928c-7f616a75f070.png)
- "Only staff can promote to leader. Ping the Doc Keeper role in #flairing_questions and have a majority of leaders confirm."

![image](https://user-images.githubusercontent.com/75290252/102170117-a1aab080-3e61-11eb-94a5-a5be946d8c78.png)
- "@ User: Successfully promoted @ Member to _Advisor/Leader_"

![image](https://user-images.githubusercontent.com/75290252/102170174-c141d900-3e61-11eb-80ca-7fb6b182ec84.png)
- "Only staff can demote leaders. Ping the Doc Keeper role in #flairing_questions and have a majority of leaders confirm, OR have the individual being demoted confirm."

![image](https://user-images.githubusercontent.com/75290252/102170388-3b725d80-3e62-11eb-9e7e-fc37a70c322d.png)
- "@ Player is already in that crew!" 
- _Mentioned in another issue_

**Comment by JettJengaGod** [comment]
@SnoreSmash put multi user flairing in another issue, will likely be a separate command.
