### ISSUE TITLE
Cb room availability function

### ISSUE THREAD

**Issue by TranquilRuhe** [JettJengaGod/scoresheetbot#51]
A way for the bot to edit a channel name with a green or red emoji to signify when a room is available for a crew. If there are no new messages for X amount of time it changes it back to green.

In addition, a command to force the room back to green in case of trolls, or people being kind and changing it.

**Comment by JettJengaGod** [comment]
Kill sheets after 60 min of inactivity. 
10 min before warn the leaders.

**Comment by JettJengaGod** [comment]
This is done except for killing sheets after 1 hr.
