### ISSUE TITLE
Sheet auto-submission to #scoresheet_history

### ISSUE THREAD

**Issue by SnoreSmash** [JettJengaGod/scoresheetbot#64]
If a sheet is done through bot, rather than posting to docs updates, it goes straight to sheet history (with header as it has been).

Reacts to confirm or deny are provided. If a doc keeper hits confirm, the header is edited to say Confirmed by @Snore#5678 .

If doc keeper hits deny, it prompts for an explanation why (dms or in the channel?), and then says "Unconfirmed by @Snore#5678: player was sent 5x in a row"

For now, doc keepers still update the merit, and should do so before reacting. But this sets us up for auto submission in future and also takes out some of the work of doing sheets

**Comment by AllanWang** [comment]
From Jett:

Current functionality:
Bot posts sheet in #docs_updates, doc keepers then manually post a screenshot of it in #sheet_history

Requested Functionality:
Bot posts sheet in #sheet_history with a confirm and deny button (only accept reacts from Doc Keeper, V2 Minion, SCS Admin
on confirm, bot edits the sheet to say confirmed by <Name of person confirming>

on deny, prompts the denier to say why they denied it and edits the scoresheet to show the denial message and who sent it
